-- Migration: record the image digest a deployment actually ran.
--
-- "Versioned deployment records with full rollback support" was hollow while
-- manifests said `nginx:latest`: rolling back re-pulled whatever `latest` meant
-- at that moment, which is frequently not what was running. The tag stays in
-- `image` because that is what a user recognises; the digest is what ran, and
-- is what rollback recreates from.
--
-- Null for every deployment recorded before this column existed. Rollback to
-- one of those falls back to the tag and says so, rather than pretending.
ALTER TABLE deployments ADD COLUMN image_digest TEXT;
