-- Migration: per-secret delivery mode.
--
-- Decrypted secrets became environment variables, which puts them in `podman
-- inspect` output and in the process environment of everything running in the
-- container. `file` mode writes them to /run/secrets/<name> on a tmpfs at mode
-- 0400 instead, following the Docker/Podman secrets convention that many images
-- already read.
--
-- Existing secrets default to 'env' — changing delivery under a running
-- application would break it, so the move is opt-in per secret.
ALTER TABLE secrets ADD COLUMN delivery_mode TEXT NOT NULL DEFAULT 'env';
