-- Team membership from a role suffix, not from one hard-coded claim key.
--
-- `team_claim_key` names exactly one key inside the group claim, which fits a
-- claim like {"API.DEVELOPERS": ["TEAM-A"]} and nothing else. The claim this was
-- written for is Keycloak's `apps_with_role`, whose keys are `<app>.<role>` and
-- whose shape is one key per application the user holds a role in:
--
--   "apps_with_role": { "podp.admin": ["PODP"], "hmi.admin": ["HMI"] }
--
-- Configured with a key, that grants membership of PODP and silently drops HMI.
-- `team_role_suffix` instead names the role — "admin" — and every key ending in
-- it contributes its teams.
ALTER TABLE oidc_config ADD COLUMN team_role_suffix TEXT;
