-- CrowdSec AppSec rules an application is exempt from.
--
-- CRS is scored, not signature-matched: a request accumulates points from many
-- rules and 949110, "Inbound Anomaly Score Exceeded", is what actually fires.
-- Applications with legitimately odd-looking traffic cross that threshold doing
-- ordinary work. Two observed in production: ProjectSend's chunked upload URLs,
-- which carry a 64-character hex signature in the query string, and versitygw's
-- S3 admin paths. Both trip the shell-expression, SQLi and PHP-injection
-- regexes.
--
-- The consequence is not a blocked request. CRS runs out-of-band, so nothing is
-- refused inline — but crowdsecurity/crowdsec-appsec-outofband turns repeats
-- into a ban, and a ban is by source address across the whole worker. A user
-- uploading a file loses every application on that host.
--
-- Stored as a JSON array mixing CRS numbers (942100) and CrowdSec rule names
-- (crowdsecurity/vpatch-git-config); the two need different removal helpers in
-- the generated AppSec configuration, so they are not normalised together.
--
-- NULL and '[]' both mean "nothing excluded", unlike exposed_ports — there is no
-- third state to distinguish here. That also fixes the direction a malformed
-- value degrades in: reading an unparseable row as "excluded nothing" leaves the
-- full ruleset in place, where the opposite would quietly disable the WAF for
-- one application.
--
-- Templates carry it so saving an application as a template and creating from it
-- does not silently re-enable rules the original had switched off.
ALTER TABLE applications ADD COLUMN appsec_disabled_rules TEXT;
ALTER TABLE application_templates ADD COLUMN appsec_disabled_rules TEXT;
