import { ROUTE_ENTRYPOINTS } from '../deploy/plan';
import { routerName } from '../domains';
import {
  FORWARDED_IDENTITY_HEADERS,
  OIDC_CALLBACK_PATH,
  normalizeIssuerUrl,
  normalizeTokenHeader,
  resolveCallbackPath,
  tokenHeaderNameError,
} from '../oidc';

// Shell assets imported as raw strings (Vite inlines at build time)
import provisionShTemplate from './shell/provision.sh?raw';

// Config templates
import traefikYmlTemplate from './shell/templates/traefik.yml?raw';
import podmanApiRoutingTlsTemplate from './shell/templates/podman-api-routing-tls.yml?raw';
import metricsRoutingTemplate from './shell/templates/metrics-routing.yml?raw';
import crowdsecMiddlewareTemplate from './shell/templates/crowdsec-middleware.yml?raw';
import globalOidcMiddlewareTemplate from './shell/templates/global-oidc-middleware.yml?raw';
import globalOidcCallbackRouterTemplate from './shell/templates/global-oidc-callback-router.yml?raw';
import crowdsecAcquisTemplate from './shell/templates/crowdsec-acquis.yml?raw';
import crowdsecAppsecAcquisTemplate from './shell/templates/crowdsec-appsec-acquis.yml?raw';
import crowdsecConfigLocalTemplate from './shell/templates/crowdsec-config-local.yml?raw';
import registriesTemplate from './shell/templates/registries.conf?raw';
import unattendedUpgradesTemplate from './shell/templates/unattended-upgrades.conf?raw';

// Helper scripts
import crowdsecRegisterSh from './shell/scripts/rudder-crowdsec-register.sh?raw';
import netavarkCleanupSh from './shell/scripts/rudder-netavark-cleanup.sh?raw';
import metricsSh from './shell/scripts/rudder-metrics.sh?raw';
import metricsHttpSh from './shell/scripts/rudder-metrics-http.sh?raw';
import traefikConfigSh from './shell/scripts/rudder-traefik-config.sh?raw';
import appsecConfigSh from './shell/scripts/rudder-appsec-config.sh?raw';
import updatesSh from './shell/scripts/rudder-updates.sh?raw';
import containerBootSh from './shell/scripts/rudder-container-boot.sh?raw';

// Systemd units
import podmanApiSocketUnit from './shell/units/podman-api-socket.service?raw';
import podmanApiTcpUnit from './shell/units/podman-api-tcp.service?raw';
import traefikContainerUnit from './shell/units/traefik-container.service?raw';
import crowdsecContainerUnit from './shell/units/crowdsec-container.service?raw';
import crowdsecRegisterUnit from './shell/units/rudder-crowdsec-register.service?raw';
import netavarkCleanupUnit from './shell/units/rudder-netavark-cleanup.service?raw';
import netavarkCleanupTimerUnit from './shell/units/rudder-netavark-cleanup.timer?raw';
import metricsUnit from './shell/units/rudder-metrics.service?raw';
import metricsTimerUnit from './shell/units/rudder-metrics.timer?raw';
import metricsHttpUnit from './shell/units/rudder-metrics-http.service?raw';
import traefikConfigUnit from './shell/units/rudder-traefik-config.service?raw';
import traefikConfigTimerUnit from './shell/units/rudder-traefik-config.timer?raw';
import appsecConfigUnit from './shell/units/rudder-appsec-config.service?raw';
import appsecConfigTimerUnit from './shell/units/rudder-appsec-config.timer?raw';
import updatesUnit from './shell/units/rudder-updates.service?raw';
import updatesTimerUnit from './shell/units/rudder-updates.timer?raw';
import containerBootUnit from './shell/units/rudder-container-boot.service?raw';

/**
 * Replace {{UPPER_SNAKE_CASE}} placeholders in a template string.
 * Only matches UPPER_SNAKE_CASE patterns to avoid colliding with
 * Go template syntax like {{.Status}} used by podman commands.
 */
function replacePlaceholders(template: string, vars: Record<string, string>): string {
  return template.replace(/\{\{([A-Z][A-Z0-9_]*)\}\}/g, (_match, key) => {
    return key in vars ? vars[key] : '';
  });
}

function toBase64(content: string): string {
  return Buffer.from(content).toString('base64');
}

/**
 * A value safe to write into a file that will be `.`-sourced by a shell.
 *
 * `traefik-config.env` is sourced, not parsed, so its values are shell syntax.
 * The tokens and URLs written there are generated by Rudder and contain nothing
 * that needs quoting, but the proxy credentials are typed by a person: a
 * password of `pa"ss\word` written bare produces an unmatched quote, and
 * sourcing the file then fails outright — taking the routing fetch with it, for
 * a reason that appears nowhere near the password field.
 *
 * Single quotes because they suppress every expansion; the only character that
 * cannot appear inside them is the single quote itself, which is closed,
 * escaped and reopened in the usual way.
 */
function shellQuote(value: string): string {
  return `'${value.replace(/'/g, `'\\''`)}'`;
}

/**
 * Container images this control plane installs on a worker.
 *
 * Pinned rather than `latest`: provisioning pulls unconditionally, so a
 * floating tag turns any re-provision into an unplanned upgrade — a Traefik
 * major version can arrive during a run triggered to change something
 * unrelated. Moving a version here is a reviewable diff, and the worker page
 * compares these against what a worker is actually running so an operator can
 * see when a re-provision would change something.
 *
 * The exact bytes are pinned further at provisioning time: the tag is resolved
 * to a repo digest after the pull and that digest goes into the systemd unit.
 */
export const PLATFORM_IMAGES = {
  traefik: { repo: 'docker.io/traefik', version: 'v3.7.10' },
  crowdsec: { repo: 'docker.io/crowdsecurity/crowdsec', version: 'v1.7.8' },
} as const;

export type PlatformComponent = keyof typeof PLATFORM_IMAGES;

/** Worker-level OIDC settings, already decrypted. */
export interface GlobalOidcConfig {
  providerURL: string;
  clientID: string;
  clientSecret: string;
  /** The plugin's `Secret` — must be exactly 32 characters. */
  secret: string;
  /**
   * Path of the shared callback URL. Defaults to `OIDC_CALLBACK_PATH`; set it
   * to whatever the worker's IdP client has registered, since providers match
   * redirect URIs by exact string.
   */
  callbackPath?: string | null;
}

/** The middleware every application on a worker with global OIDC references. */
export const GLOBAL_OIDC_MIDDLEWARE = 'global-oidc';

/**
 * Header names an application wants its OAuth tokens delivered under.
 *
 * Both are optional and a missing one means "do not forward that token" — the
 * name is the switch, because a token an application does not know the name of
 * is only weight on every request.
 */
export interface AppTokenHeaders {
  idTokenHeader?: string | null;
  accessTokenHeader?: string | null;
}

/** The token headers worth generating for an application, or undefined. */
export function usableTokenHeaders(
  headers: AppTokenHeaders | null | undefined,
): AppTokenHeaders | undefined {
  if (!headers) return undefined;
  const keep = (raw: string | null | undefined) => {
    const name = normalizeTokenHeader(raw);
    // Dropped rather than rendered. These names are validated where they are
    // saved, so reaching here means a row written before that validation
    // existed — and an unusable `Name:` would make the plugin fail to build,
    // which costs every application on the worker its routing, not just this
    // one.
    if (name && tokenHeaderNameError(name)) {
      console.warn(`[traefik] Ignoring unusable OIDC token header name "${name}".`);
      return null;
    }
    return name;
  };
  const idTokenHeader = keep(headers.idTokenHeader);
  const accessTokenHeader = keep(headers.accessTokenHeader);
  if (!idTokenHeader && !accessTokenHeader) return undefined;
  return { idTokenHeader, accessTokenHeader };
}

/**
 * The middleware an application gets instead of the shared one when it asks for
 * its tokens.
 *
 * A full copy of the worker's OIDC middleware, not an extra one in the chain:
 * the plugin's `Headers` are part of its configuration, so per-application
 * headers mean a per-application instance. It is the same client, the same
 * `Secret` and the same session cookie, so it accepts the session any other
 * application on the worker established — the only difference is what it adds
 * to the request on the way through.
 *
 * `-oidc-tokens` rather than `-global-oidc` so it cannot collide with the
 * `<app>-oidc` a per-application OIDC configuration generates: no application
 * name produces both, because that path always appends `-oidc` last.
 */
export function appOidcMiddlewareName(appName: string): string {
  return `${routerName(appName)}-oidc-tokens`;
}

/**
 * Wrap a plugin template so it survives Traefik's own templating.
 *
 * Traefik runs every *dynamic* configuration file through Go's `text/template`
 * before parsing it, and both files this renderer feeds are dynamic ones —
 * `global-oidc.yml` on a labels-mode worker, `routes.yml` on an http-mode one.
 * An unescaped `{{ .claims.email }}` is therefore evaluated by Traefik, against
 * a context that has no `claims`, and the plugin receives the empty string it
 * produced. Wrapping the expression in a raw string literal makes Traefik's
 * pass emit it verbatim and leaves the evaluation to the plugin.
 *
 * The expression must not contain a backtick, which would close the literal.
 * Nothing here interpolates one: header names are validated to letters, digits
 * and hyphens, and the claim paths are constants.
 */
function pluginTemplate(expression: string): string {
  return '{{`' + expression + '`}}';
}

/** A claim, or the empty string when the provider did not send it. */
function claim(name: string): string {
  return `{{ with .claims.${name} }}{{ . }}{{ end }}`;
}

/**
 * The `Headers` block for one OIDC middleware, indented to sit under the
 * plugin's configuration.
 *
 * The identity headers are unconditional: they are what makes an application
 * able to log a user in without speaking OIDC itself, they are the same for
 * every application on the worker, and they cost a few dozen bytes a request.
 * Every value is guarded with `{{ with }}` so a claim the provider did not send
 * renders as the empty string — Go prints a missing map key as `<no value>`,
 * and an application would happily create an account named that.
 *
 * `Authorization` is never one of them. An application that uses that header
 * for its own API tokens would find them replaced on every request, which is a
 * failure the automatic set must not be able to cause; an application that
 * wants a bearer token can ask for one by name.
 */
function oidcHeadersBlock(tokens?: AppTokenHeaders): string {
  // Destructured from the shared constant rather than written out again: the
  // same names are what `tokenHeaderNameError` refuses to let an application
  // claim for a token, and a name that appeared in one list but not the other
  // would let a token quietly overwrite an identity header.
  const [USER, EMAIL, PREFERRED_USERNAME, GROUPS] = FORWARDED_IDENTITY_HEADERS;

  const entries: Array<{ name: string; value?: string; values?: string }> = [
    // preferred_username is what an IdP means by "the name this person logs in
    // with"; sub is always present but is an opaque id, so it is the fallback
    // rather than the first choice.
    {
      name: USER,
      value: `{{ with .claims.preferred_username }}{{ . }}{{ else }}${claim('sub')}{{ end }}`,
    },
    { name: EMAIL, value: claim('email') },
    { name: PREFERRED_USERNAME, value: claim('preferred_username') },
    // `Values` rather than `Value`: it produces one header per group, the way
    // oauth2-proxy does, and — unlike `Value` — the plugin *deletes* the header
    // when the array is empty, so an application that receives no groups also
    // receives no client-supplied leftovers under that name. The `{{ else }}`
    // keeps it valid JSON when the provider sends no groups claim at all.
    {
      name: GROUPS,
      values: '{{ with .claims.groups }}{{ . | mapToJsonArray }}{{ else }}[]{{ end }}',
    },
  ];

  for (const [header, token] of [
    [tokens?.idTokenHeader, '.idToken'],
    [tokens?.accessTokenHeader, '.accessToken'],
  ] as const) {
    if (!header) continue;
    // Only `Authorization` gets the scheme. Everywhere else the bare token is
    // what an application expects to find, and a stray "Bearer " in front of it
    // is a decode failure the operator has to guess at.
    const bare = `{{ ${token} }}`;
    entries.push({
      name: header,
      value: header.toLowerCase() === 'authorization' ? `Bearer ${bare}` : bare,
    });
  }

  return entries
    .map((entry) => {
      const field = entry.values === undefined
        ? `              Value: "${pluginTemplate(entry.value!)}"`
        : `              Values: "${pluginTemplate(entry.values)}"`;
      return `            - Name: "${entry.name}"\n${field}`;
    })
    .join('\n');
}

/**
 * Render one `traefik-oidc-auth` middleware, indented under `http.middlewares`.
 *
 * The template is a fragment rather than a document because this runs more than
 * once per worker: `Headers` is part of a middleware's configuration, so an
 * application that wants different headers needs a different middleware, and
 * the only difference between the copies is what they add to the request.
 */
function renderOidcMiddleware(
  name: string,
  baseDomain: string,
  oidcConfig: GlobalOidcConfig,
  tokens?: AppTokenHeaders,
): string {
  return replacePlaceholders(globalOidcMiddlewareTemplate, {
    OIDC_MIDDLEWARE_NAME: name,
    BASE_DOMAIN: baseDomain,
    OIDC_PROVIDER_URL: normalizeIssuerUrl(oidcConfig.providerURL) ?? oidcConfig.providerURL,
    OIDC_CLIENT_ID: oidcConfig.clientID,
    OIDC_CLIENT_SECRET: oidcConfig.clientSecret,
    OIDC_SECRET: oidcConfig.secret,
    OIDC_CALLBACK_PATH: resolveCallbackPath(oidcConfig.callbackPath),
    OIDC_HEADERS: oidcHeadersBlock(tokens),
  }).trimEnd();
}

/** An application that wants its tokens, and the router it is reached through. */
export interface AppTokenForwarding extends AppTokenHeaders {
  /** The router base name — `appOidcMiddlewareName` derives the middleware from it. */
  routerBase: string;
}

/**
 * Render `/etc/traefik/dynamic/global-oidc.yml` for a worker.
 *
 * Single source of truth for the global OIDC middleware: used both when
 * provisioning a worker from scratch and when pushing a config change to a
 * running worker over SSH, so the two can never drift apart.  The same text is
 * parsed and merged into the served routing document for `http`-mode workers,
 * so the two routing modes cannot drift apart either.
 *
 * The provider URL is normalised here rather than only where it is saved: rows
 * written before that validation existed still hold discovery URLs, and a
 * worker whose OIDC has silently never worked should start working on its next
 * provisioning run rather than waiting for someone to re-save the form.
 *
 * `tokenApps` adds one copy of the middleware per application that asked for
 * its tokens. Passing none renders exactly what this function rendered before
 * they existed, plus the identity headers.
 */
export function renderGlobalOidcConfig(
  baseDomain: string,
  oidcConfig: GlobalOidcConfig,
  tokenApps: readonly AppTokenForwarding[] = [],
): string {
  const middlewares = [renderOidcMiddleware(GLOBAL_OIDC_MIDDLEWARE, baseDomain, oidcConfig)];

  for (const app of tokenApps) {
    const tokens = usableTokenHeaders(app);
    if (!tokens) continue;
    middlewares.push(
      renderOidcMiddleware(appOidcMiddlewareName(app.routerBase), baseDomain, oidcConfig, tokens),
    );
  }

  return [
    'http:',
    '  middlewares:',
    ...middlewares,
    '  routers:',
    replacePlaceholders(globalOidcCallbackRouterTemplate, { BASE_DOMAIN: baseDomain }).trimEnd(),
    '',
  ].join('\n');
}

export interface ProvisioningOptions {
  baseDomain?: string;
  bouncerKey?: string;
  oidcConfig?: GlobalOidcConfig;
  /**
   * Applications on this worker that forward their OAuth tokens.
   *
   * Provisioning writes `global-oidc.yml` and records the worker as applied, so
   * the file it writes has to contain every middleware the routers will name —
   * otherwise a `labels`-mode worker comes back from a re-provision with its
   * token-forwarding applications 404ing, and nothing says the push is stale.
   */
  oidcTokenApps?: readonly AppTokenForwarding[];
  /** SSH port to keep open in the host firewall alongside 22. */
  sshPort?: number;
  /**
   * Install pending host package updates during this run. Defaults to true —
   * re-provisioning should be a patching event, not a config refresh that
   * leaves a year-old kernel in place.
   *
   * Turning it off still reports what is pending; it only skips the install,
   * for environments that patch on their own schedule and for runs where the
   * extra minutes matter.
   */
  applyUpdates?: boolean;
  /**
   * Routing configuration delivery, for workers in `http` routing mode. When
   * absent the worker stays on container labels and any previously installed
   * routes.yml is removed — the two must never both define a router.
   */
  routingConfig?: {
    /** Absolute URL of this worker's config endpoint on the control plane. */
    endpoint: string;
    /** Bearer token, already decrypted. */
    token: string;
    /**
     * HTTP Basic credentials for a proxy in front of the control plane, already
     * decrypted. When present the worker sends these as `Authorization: Basic`
     * and its own token as `X-Rudder-Config-Token`, because the outer layer has
     * to be satisfied before the request reaches Rudder at all.
     */
    basicUser?: string | null;
    basicPassword?: string | null;
  };
  /**
   * This worker's own credential, planted regardless of routing mode.
   *
   * `POST /api/workers/register` needs it to tell which worker is calling — the
   * shared registration secret says only that the caller is *some* worker, and
   * the endpoint picks its target from the hostname in the body. It is the same
   * value as `routingConfig.token` when there is one; it gets its own file
   * because `traefik-config.env` is deleted on a labels-mode run, and workers in
   * both modes register.
   */
  workerToken?: string;
  /**
   * CrowdSec AppSec exclusion delivery, planted regardless of routing mode.
   *
   * Which CRS rules an application is exempt from has nothing to do with how
   * Traefik learns its routes, and a labels-mode worker whose users are being
   * banned by a false positive needs this exactly as much as an http-mode one.
   *
   * Absent when the control plane has no `PUBLIC_URL` to hand out. The worker
   * then keeps whatever exclusions it already has rather than losing them —
   * `rudder-appsec-config.sh` exits quietly with no endpoint configured.
   */
  appsecConfig?: {
    /** Absolute URL of this worker's AppSec config endpoint. */
    endpoint: string;
    /** Bearer token, already decrypted. The same worker token. */
    token: string;
    /** @see routingConfig.basicUser — the same proxy, the same credentials. */
    basicUser?: string | null;
    basicPassword?: string | null;
  };
}

export function generateProvisioningScript(
  workerName: string,
  options: ProvisioningOptions = {},
): string {
  const {
    baseDomain,
    bouncerKey: bouncerKeyParam,
    oidcConfig,
    oidcTokenApps,
    sshPort,
    routingConfig,
    workerToken,
    appsecConfig,
    applyUpdates = true,
  } = options;
  const bouncerKey = bouncerKeyParam || '';
  const podmanApiDomain = baseDomain ? `podman-api.${baseDomain}` : '';
  const acmeEmail = baseDomain ? `admin@${baseDomain}` : `admin@${workerName}.local`;

  // Template variables for {{PLACEHOLDER}} substitution
  const templateVars: Record<string, string> = {
    ACME_EMAIL: acmeEmail,
    BOUNCER_KEY: bouncerKey,
    BASE_DOMAIN: baseDomain || '',
    PODMAN_API_DOMAIN: podmanApiDomain,
    WORKER_NAME: workerName,
  };

  // Render config templates with runtime values
  const traefikYml = replacePlaceholders(traefikYmlTemplate, templateVars);
  // No base domain means no Podman API route at all.
  //
  // There used to be a "notls" variant here for that case: a catch-all
  // ``PathPrefix(`/`)`` router, `tls: {}`, and — crucially — no `clientAuth`
  // block. Traefik listens on 443 and the host firewall admits 443, so every
  // worker provisioned without a base domain published the root-equivalent
  // Podman API to anyone who could reach it. `POST /containers/create` with a
  // privileged bind mount of `/` is host takeover.
  //
  // It cannot be fixed in place: Traefik binds `tls.options` to a router's SNI,
  // and a catch-all has no Host rule to bind to, so `RequireAndVerifyClientCert`
  // there is silently ignored or applied to every connection. Without a
  // hostname there is nothing to route, so nothing is routed — the API stays on
  // 127.0.0.1:8080 for local use. `/api/workers/provision` refuses these
  // workers up front; this is the second layer, so the insecure document cannot
  // be generated even by a caller that bypasses the route.
  const podmanApiRouting = baseDomain
    ? replacePlaceholders(podmanApiRoutingTlsTemplate, templateVars)
    : '';
  const metricsRouting = baseDomain
    ? replacePlaceholders(metricsRoutingTemplate, templateVars)
    : '';
  const crowdsecMiddleware = replacePlaceholders(crowdsecMiddlewareTemplate, templateVars);
  const globalOidcMiddleware = (oidcConfig && baseDomain)
    ? renderGlobalOidcConfig(baseDomain, oidcConfig, oidcTokenApps)
    : '';

  // Render scripts/units that need variable substitution
  const crowdsecRegister = replacePlaceholders(crowdsecRegisterSh, templateVars);
  const crowdsecContainer = replacePlaceholders(crowdsecContainerUnit, templateVars);

  // Build provision.sh placeholder map
  const provisionVars: Record<string, string> = {
    WORKER_NAME: workerName,
    BOUNCER_KEY: bouncerKey,
    BASE_DOMAIN: baseDomain || '',
    SSH_PORT: String(sshPort && sshPort > 0 ? sshPort : 22),
    CONFIG_ENDPOINT: routingConfig?.endpoint ?? '',
    CONFIG_TOKEN: routingConfig?.token ?? '',
    // Quoted, unlike the generated values above: these are operator input.
    CONFIG_BASIC_USER: routingConfig?.basicUser ? shellQuote(routingConfig.basicUser) : '',
    CONFIG_BASIC_PASS: routingConfig?.basicPassword ? shellQuote(routingConfig.basicPassword) : '',
    APPSEC_ENDPOINT: appsecConfig?.endpoint ?? '',
    APPSEC_TOKEN: appsecConfig?.token ?? '',
    APPSEC_BASIC_USER: appsecConfig?.basicUser ? shellQuote(appsecConfig.basicUser) : '',
    APPSEC_BASIC_PASS: appsecConfig?.basicPassword ? shellQuote(appsecConfig.basicPassword) : '',
    WORKER_TOKEN: workerToken ?? '',
    APPLY_UPDATES: applyUpdates ? '1' : '0',
    TRAEFIK_IMAGE_VERSION: PLATFORM_IMAGES.traefik.version,
    CROWDSEC_IMAGE_VERSION: PLATFORM_IMAGES.crowdsec.version,

    // Config templates (base64-encoded)
    TRAEFIK_YML_B64: toBase64(traefikYml),
    PODMAN_API_ROUTING_B64: podmanApiRouting ? toBase64(podmanApiRouting) : '',
    METRICS_ROUTING_B64: metricsRouting ? toBase64(metricsRouting) : '',
    CROWDSEC_MIDDLEWARE_B64: toBase64(crowdsecMiddleware),
    GLOBAL_OIDC_MIDDLEWARE_B64: globalOidcMiddleware ? toBase64(globalOidcMiddleware) : '',
    CROWDSEC_ACQUIS_B64: toBase64(crowdsecAcquisTemplate),
    CROWDSEC_APPSEC_ACQUIS_B64: toBase64(crowdsecAppsecAcquisTemplate),
    CROWDSEC_CONFIG_LOCAL_B64: toBase64(crowdsecConfigLocalTemplate),
    REGISTRIES_B64: toBase64(registriesTemplate),
    UNATTENDED_UPGRADES_B64: toBase64(unattendedUpgradesTemplate),

    // Systemd units (base64-encoded)
    PODMAN_API_SOCKET_SERVICE_B64: toBase64(podmanApiSocketUnit),
    PODMAN_API_TCP_SERVICE_B64: toBase64(podmanApiTcpUnit),
    TRAEFIK_SERVICE_B64: toBase64(traefikContainerUnit),
    CROWDSEC_SERVICE_B64: toBase64(crowdsecContainer),
    CROWDSEC_REGISTER_SERVICE_B64: toBase64(crowdsecRegisterUnit),
    NETAVARK_CLEANUP_SERVICE_B64: toBase64(netavarkCleanupUnit),
    NETAVARK_CLEANUP_TIMER_B64: toBase64(netavarkCleanupTimerUnit),
    METRICS_SERVICE_B64: toBase64(metricsUnit),
    METRICS_TIMER_B64: toBase64(metricsTimerUnit),
    METRICS_HTTP_SERVICE_B64: toBase64(metricsHttpUnit),
    TRAEFIK_CONFIG_SERVICE_B64: toBase64(traefikConfigUnit),
    TRAEFIK_CONFIG_TIMER_B64: toBase64(traefikConfigTimerUnit),
    APPSEC_CONFIG_SERVICE_B64: toBase64(appsecConfigUnit),
    APPSEC_CONFIG_TIMER_B64: toBase64(appsecConfigTimerUnit),
    UPDATES_SERVICE_B64: toBase64(updatesUnit),
    UPDATES_TIMER_B64: toBase64(updatesTimerUnit),
    CONTAINER_BOOT_SERVICE_B64: toBase64(containerBootUnit),

    // Helper scripts (base64-encoded)
    CROWDSEC_REGISTER_SCRIPT_B64: toBase64(crowdsecRegister),
    NETAVARK_CLEANUP_SCRIPT_B64: toBase64(netavarkCleanupSh),
    METRICS_SCRIPT_B64: toBase64(metricsSh),
    METRICS_HTTP_SCRIPT_B64: toBase64(metricsHttpSh),
    TRAEFIK_CONFIG_SCRIPT_B64: toBase64(traefikConfigSh),
    APPSEC_CONFIG_SCRIPT_B64: toBase64(appsecConfigSh),
    UPDATES_SCRIPT_B64: toBase64(updatesSh),
    CONTAINER_BOOT_SCRIPT_B64: toBase64(containerBootSh),
  };

  return replacePlaceholders(provisionShTemplate, provisionVars);
}

// ── Traefik label generation ──────────────────────────────────────────
// Generate Podman/Docker labels for Traefik routing with HTTPS, Let's Encrypt TLS-ALPN-01, and CrowdSec WAF
// Traefik listens on port 443 only. No port 80 needed.
// Traefik runs with host networking so it proxies to host-mapped container ports via 127.0.0.1
// All routes are protected by CrowdSec AppSec middleware (crowdsec@file) by default.
// Per-application rate limiting and OIDC auth can be added via options.
export interface AppMiddlewareOptions {
  rateLimitAvg?: number;      // requests/second average (Traefik rateLimit)
  rateLimitBurst?: number;    // max burst size
  authType?: 'none' | 'oidc';
  authConfig?: {              // Per-app OIDC provider settings
    providerURL: string;      // e.g. https://accounts.google.com
    clientID: string;
    clientSecret: string;
    /** Plugin `Secret` — must be exactly 32 characters. */
    sessionEncryptionKey: string;
    /**
     * Callback path on the application's own host.  Per-app OIDC deliberately
     * does *not* use the worker's shared `auth.<base>` callback: that host
     * carries the global middleware and a different IdP client.
     */
    callbackURL?: string;     // default: /oidc/callback
    /**
     * Not supported by the plugin — `AssertClaims` matches claim values by
     * exact string equality, with no suffix or pattern matching.  Deploys that
     * set this are rejected rather than silently losing the restriction.
     */
    allowedUserDomains?: string[];
    allowedUsers?: string[];  // → Authorization.AssertClaims on the `email` claim
    excludedURLs?: string[];  // → BypassAuthenticationRule (PathPrefix)
    scopes?: string[];
  };
  healthCheckPath?: string;   // Traefik health check endpoint, e.g. /health
  useGlobalAuth?: boolean;    // whether to apply global OIDC auth (default: true if global OIDC is configured)
  /**
   * Header names for the OAuth tokens, when this application wants them.
   *
   * Only meaningful under worker-level OIDC — an application with its own
   * per-app OIDC configuration is not routed through the worker's middleware,
   * so there is nothing here to copy.
   */
  tokenHeaders?: AppTokenHeaders;
}

/**
 * Does this application's router carry the worker's global OIDC middleware?
 *
 * Exported because two places have to agree on the answer: the labels that
 * *reference* the middleware, and the renderer that *defines* the per-app copy
 * of it. If they disagreed in the direction of "referenced but not defined",
 * Traefik would drop the router and the application would 404.
 */
export function usesGlobalOidc(
  globalOidcEnabled: boolean,
  middlewareOpts?: AppMiddlewareOptions,
): boolean {
  if (!globalOidcEnabled) return false;
  if (middlewareOpts?.authType === 'oidc' && middlewareOpts.authConfig) return false;
  if (middlewareOpts?.authType === 'none') return false;
  return middlewareOpts?.useGlobalAuth !== false;
}

/**
 * Is this an absolute URL path safe to place inside a Traefik matcher?
 *
 * Must start with `/`, and may not contain a backtick (which would close the
 * matcher), whitespace, or the characters Traefik's rule grammar reads as
 * operators and grouping. Deliberately narrow: this guards a value that becomes
 * authentication logic.
 */
export function isPlainPathPrefix(path: unknown): path is string {
  return (
    typeof path === 'string' &&
    path.startsWith('/') &&
    path.length <= 2048 &&
    !/[`'"()|&,\s\\]/.test(path)
  );
}

/** One of an application's routes, as the label generator needs it. */
export interface TraefikRoutePort {
  /** `routeKey(index)` — empty for the 443 route, `p1`… for the rest. */
  key: string;
  /** Traefik entryPoint name, from `ROUTE_ENTRYPOINTS`. */
  entryPoint: string;
  /** Host port this route's service proxies to. */
  hostPort: number;
}

/** Router and service identifier for one route of `safeName`. */
function routeIdentifier(safeName: string, key: string): string {
  return key ? `${safeName}-${key}` : safeName;
}

export function generateTraefikLabelsForApp(
  appName: string,
  domain: string,
  /**
   * A bare host port is the 443 route and nothing else — the shape every caller
   * used before extra entryPoints existed, kept so a single-route application's
   * labels are byte-identical to what it has been running.
   */
  targetPort: number | readonly TraefikRoutePort[],
  enableWebSocket: boolean = true,
  middlewareOpts?: AppMiddlewareOptions,
  globalOidcEnabled: boolean = false
): Record<string, string> {
  const safeName = routerName(appName);
  const routes: readonly TraefikRoutePort[] =
    typeof targetPort === 'number'
      ? [{ key: '', entryPoint: ROUTE_ENTRYPOINTS[0], hostPort: targetPort }]
      : targetPort;

  // Every route's chain: the WAF, the security headers, and the rate limit when
  // one is set. None of these is interactive and none of them breaks a machine
  // client, which is what makes "the extra ports are not a way around the WAF"
  // a fact rather than a hope.
  const middlewares: string[] = ['crowdsec@file', 'security-headers@file'];

  const labels: Record<string, string> = { 'traefik.enable': 'true' };

  for (const route of routes) {
    const id = routeIdentifier(safeName, route.key);
    // HTTPS router with Let's Encrypt TLS-ALPN-01 (no port 80 needed).
    // Every route of a container shares the hostname and therefore the
    // certificate; only the entryPoint and the identifier differ.
    labels[`traefik.http.routers.${id}-secure.rule`] = `Host(\`${domain}\`)`;
    labels[`traefik.http.routers.${id}-secure.entrypoints`] = route.entryPoint;
    labels[`traefik.http.routers.${id}-secure.tls`] = 'true';
    labels[`traefik.http.routers.${id}-secure.tls.certresolver`] = 'letsencrypt';
    labels[`traefik.http.routers.${id}-secure.service`] = id;

    // Service: Traefik on host network proxies to container's host-mapped port
    labels[`traefik.http.services.${id}.loadbalancer.server.url`] =
      `http://127.0.0.1:${route.hostPort}`;
  }

  // Health check — Traefik marks backend as down if it fails.
  //
  // The 443 service only. `healthCheckPath` is one path for the whole
  // application, and an application publishing several ports is publishing
  // several *services*: probing the web UI's health path against the S3 API
  // would 404, Traefik would mark that backend down, and the port would go dark
  // for a reason that has nothing to do with it.
  if (middlewareOpts?.healthCheckPath) {
    labels[`traefik.http.services.${safeName}.loadbalancer.healthcheck.path`] = middlewareOpts.healthCheckPath;
    labels[`traefik.http.services.${safeName}.loadbalancer.healthcheck.interval`] = '10s';
    labels[`traefik.http.services.${safeName}.loadbalancer.healthcheck.timeout`] = '5s';
  }

  // Per-app rate limiting (Traefik built-in rateLimit middleware)
  if (middlewareOpts?.rateLimitAvg && middlewareOpts.rateLimitAvg > 0) {
    const rlName = `${safeName}-ratelimit`;
    labels[`traefik.http.middlewares.${rlName}.ratelimit.average`] = String(middlewareOpts.rateLimitAvg);
    labels[`traefik.http.middlewares.${rlName}.ratelimit.burst`] = String(middlewareOpts.rateLimitBurst || middlewareOpts.rateLimitAvg * 2);
    labels[`traefik.http.middlewares.${rlName}.ratelimit.period`] = '1s';
    middlewares.push(`${rlName}@docker`);
  }

  // Everything above applies to every route. Everything from here — the OIDC
  // middleware, global or per-application — applies to the 443 route alone.
  //
  // Not an oversight, and not a weaker chain for the extra ports. OIDC is an
  // interactive browser redirect; the extra entryPoints carry machine traffic —
  // an S3 endpoint, an admin API, a scrape target — and no such client can
  // follow a redirect to an HTML login. Putting the flow in front of one does
  // not protect it, it makes it unusable. Where 443 and 1443 serve different
  // services, an unauthenticated route to the second is not a way around the
  // first: it is a different endpoint, and protecting it is the application's
  // job — an API key, signature auth, mTLS.
  //
  // The application page states which routes this covers, so an operator who
  // switched authentication on can see what it reaches.
  const sharedMiddlewares = [...middlewares];

  // Global OIDC auth (if enabled and not overridden by per-app OIDC or explicitly disabled)
  const hasPerAppOidc = middlewareOpts?.authType === 'oidc' && middlewareOpts.authConfig;

  if (usesGlobalOidc(globalOidcEnabled, middlewareOpts)) {
    // The per-application copy when this application asked for its tokens, the
    // shared one otherwise. Both are defined by `renderGlobalOidcConfig`, which
    // is handed the same list of applications this decision is made from.
    const tokens = usableTokenHeaders(middlewareOpts?.tokenHeaders);
    middlewares.push(
      tokens ? `${appOidcMiddlewareName(safeName)}@file` : `${GLOBAL_OIDC_MIDDLEWARE}@file`,
    );
  }

  // Per-app OIDC auth (sevensolutions/traefik-oidc-auth plugin).
  //
  // Unlike the worker-global middleware this uses a *relative* CallbackUri, so
  // the plugin intercepts /oidc/callback on the application's own host.  The
  // shared auth.<base> host belongs to the global middleware and a different
  // IdP client registration.
  if (middlewareOpts?.authType === 'oidc' && middlewareOpts.authConfig) {
    const oidcName = `${safeName}-oidc`;
    const cfg = middlewareOpts.authConfig;
    const p = `traefik.http.middlewares.${oidcName}.plugin.traefik-oidc-auth`;

    labels[`${p}.LogLevel`] = 'INFO';
    labels[`${p}.Secret`] = cfg.sessionEncryptionKey;
    // Same rule as the worker-level middleware: the plugin appends the
    // discovery path itself. Per-app config is an opaque JSON blob rather than
    // a column, so this is the only place it can be corrected.
    labels[`${p}.Provider.Url`] = normalizeIssuerUrl(cfg.providerURL) ?? cfg.providerURL;
    labels[`${p}.Provider.ClientId`] = cfg.clientID;
    labels[`${p}.Provider.ClientSecret`] = cfg.clientSecret;
    labels[`${p}.Provider.UsePkce`] = 'true';
    labels[`${p}.CallbackUri`] = cfg.callbackURL || OIDC_CALLBACK_PATH;
    labels[`${p}.SessionCookie.Secure`] = 'true';
    labels[`${p}.SessionCookie.HttpOnly`] = 'true';
    labels[`${p}.SessionCookie.SameSite`] = 'lax';

    const scopes = cfg.scopes?.length ? cfg.scopes : ['openid', 'profile', 'email'];
    scopes.forEach((scope, i) => {
      labels[`${p}.Scopes[${i}]`] = scope;
    });

    // Claim assertions are only re-evaluated per request when asked; without
    // this a session minted before a claim changed keeps its access.
    labels[`${p}.Authorization.CheckOnEveryRequest`] = 'true';
    if (cfg.allowedUsers?.length) {
      labels[`${p}.Authorization.AssertClaims[0].Name`] = 'email';
      cfg.allowedUsers.forEach((u, i) => {
        labels[`${p}.Authorization.AssertClaims[0].AnyOf[${i}]`] = u;
      });
    }

    // excludedURLs are path prefixes; the plugin takes a single Traefik-style rule.
    //
    // Each path goes inside a backtick-quoted matcher, so an unfiltered value
    // could close it and append rule logic of its own: a path of
    // `` /x`) || Method(`GET `` turned a path exclusion into "bypass
    // authentication for every GET". Anything that is not a plain absolute path
    // is dropped rather than escaped — there is no legitimate exclusion that
    // needs these characters, and a silently rewritten rule is worse than a
    // missing one.
    if (cfg.excludedURLs?.length) {
      const paths = cfg.excludedURLs.filter(isPlainPathPrefix);
      if (paths.length !== cfg.excludedURLs.length) {
        console.warn(
          `[traefik] Dropped ${cfg.excludedURLs.length - paths.length} OIDC exclusion path(s) for ` +
            `"${safeName}" that were not plain absolute paths.`,
        );
      }
      if (paths.length) {
        labels[`${p}.BypassAuthenticationRule`] = paths
          .map((path) => `PathPrefix(\`${path}\`)`)
          .join(' || ');
      }
    }

    middlewares.push(`${oidcName}@docker`);
  }

  // Set the middleware chain on the routers: the full one on 443, the shared
  // one — everything except authentication — on the rest.
  const middlewareChain = middlewares.join(',');
  const sharedChain = sharedMiddlewares.join(',');
  for (const route of routes) {
    const id = routeIdentifier(safeName, route.key);
    labels[`traefik.http.routers.${id}-secure.middlewares`] = route.key ? sharedChain : middlewareChain;
  }

  // The 443 route only. A WebSocket router per port is speculative until
  // something asks for one, and each is another place a middleware list can
  // drift from the primary's — which is exactly what happened to this one.
  if (enableWebSocket) {
    labels[`traefik.http.routers.${safeName}-secure-ws.rule`] =
      `Host(\`${domain}\`) && Header(\`Connection\`, \`Upgrade\`) && Header(\`Upgrade\`, \`websocket\`)`;
    labels[`traefik.http.routers.${safeName}-secure-ws.entrypoints`] = 'websecure';
    labels[`traefik.http.routers.${safeName}-secure-ws.tls`] = 'true';
    labels[`traefik.http.routers.${safeName}-secure-ws.tls.certresolver`] = 'letsencrypt';
    labels[`traefik.http.routers.${safeName}-secure-ws.service`] = safeName;
    // The same chain as the main router, authentication included.
    //
    // This router used to drop every middleware whose name contained `-oidc` —
    // both `global-oidc@file` and the per-app one — on the grounds that a
    // WebSocket client cannot follow an OAuth redirect.  But Traefik picks a
    // router by matching its rule, and this rule matches on two request headers
    // that any HTTP client can send: `Connection: Upgrade` and
    // `Upgrade: websocket` on an ordinary GET reached the application with no
    // session at all, on any method.  Authentication that two headers turn off
    // is not authentication.
    //
    // The redirect concern was real but is the plugin's to make: it answers an
    // unauthenticated non-HTML request with 401 rather than a redirect, which is
    // what a WebSocket client should see.  A browser opening a socket carries
    // the session cookie the page's own login established, so real WebSocket
    // traffic from a signed-in user still passes.
    labels[`traefik.http.routers.${safeName}-secure-ws.middlewares`] = middlewareChain;
  }

  return labels;
}
